[window]
opacity = 0.85

[colors]
transparent_background_colors = true

[colors.primary]
background = "#181a1f"
foreground = "#b9bec6"


[colors.normal]
black   = "#181a1f"
red     = "#b31414"
green   = "#d12b2b"
yellow  = "#9e1a1a"
blue    = "#ad2222"
magenta = "#c3c8d0"
cyan    = "#8f949c"
white   = "#b9bec6"

[colors.bright]
black   = "#4b515b"
red     = "#b31414"
green   = "#d12b2b"
yellow  = "#9e1a1a"
blue    = "#ad2222"
magenta = "#c3c8d0"
cyan    = "#8f949c"
white   = "#eceff2"

[colors.cursor]
text   = "#181a1f"
cursor = "#b9bec6"

[colors.selection]
text = "#b9bec6"
background = "#ad2222"
