accent = "#ad2222"
cursor = "#b9bec6"
foreground = "#b9bec6"
background = "#181a1f"
selection_foreground = "#b9bec6"
selection_background = "#ad2222"

color0 = "#181a1f"
color1 = "#b31414"
color2 = "#d12b2b"
color3 = "#9e1a1a"
color4 = "#ad2222"
color5 = "#c3c8d0"
color6 = "#8f949c"
color7 = "#b9bec6"
color8 = "#4b515b"
color9 = "#b31414"
color10 = "#d12b2b"
color11 = "#9e1a1a"
color12 = "#ad2222"
color13 = "#c3c8d0"
color14 = "#8f949c"
color15 = "#eceff2"
